apiVersion: v1
kind: Service
metadata:
  name: ang-service
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: ang-port
    protocol: TCP
  selector:
    app: sampleapp
  type: NodePort
