apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: k8s-demo
        image: uzair158/av-app-image:latest
        ports:
        - name: ang-port
          containerPort: 80
